version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=4096  # Increase to 4GB
    deploy:
      resources:
        limits:
          memory: 5G  # Total memory allocation for the container
